### ISSUE TITLE
feature: Allow user lists / groups

### ISSUE THREAD

**Issue by StaticRocket** [dyladan/auto-assign-owners#22]
Occasionally the same core group of users will want to be used for multiple directories. Right now if it's exactly the same list we can use YAML anchors to prevent copying large sections. Unfortunately this falls apart when you want to add on an additional user for a specific directory, as YAML does not allow merging arrays/sequences.

For that I'd like to request the concept of user lists / groups.

This can be done 2 different ways:

1. The introduction of a list config section. The lists are just keys containing standard usernames that will be inserted into the request before it hits the GitHub API.

```yml
lists:
  doc_parsers:
    - usera
    - userb
components:
  "*.md":
    - doc_parsers
  "*.rst":
    - doc_parsers
    - userrst
```

2. Allowing the parsing of lists of lists in the YAML config where this is then flattened. Then we can continue to use anchors and aliases without needing to parse additional sections manually. In the below example `lists` is simply ignored by the config parser and the YAML parser will automatically expand the arrays such that `"*.md": [["usera", "userb"]]` and `"*.rst": [["usera", "userb"], "userrst"]`. Then the array can be flattened and processed as is.

```yml
lists:
  doc_parsers: &doc_list
    - usera
    - userb
components:
  "*.md":
    - *doc_list
  "*.rst":
    - *doc_list
    - userrst
```

---

This will also be useful for repositories that do not want to use a personal access token to allow for the direct usage of GitHub groups.
